{"timestamp": "2025-07-23T20:42:13.358060", "level": "ERROR", "message": "\u001b[2m2025-07-23T23:42:13.357909Z\u001b[0m [\u001b[31m\u001b[1merror    \u001b[0m] \u001b[1mdatabase_initialization_error \u001b[0m [\u001b[0m\u001b[1m\u001b[34mapp.services.database\u001b[0m]\u001b[0m \u001b[36menvironment\u001b[0m=\u001b[35mdevelopment\u001b[0m \u001b[36merror\u001b[0m=\u001b[35m'(psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: FATAL:  role \"ali_user\" does not exist\\n\\n(Background on this error at: https://sqlalche.me/e/20/e3q8)'\u001b[0m \u001b[36mfilename\u001b[0m=\u001b[35mdatabase.py\u001b[0m \u001b[36mfunc_name\u001b[0m=\u001b[35m__init__\u001b[0m \u001b[36mlineno\u001b[0m=\u001b[35m62\u001b[0m \u001b[36mmodule\u001b[0m=\u001b[35mdatabase\u001b[0m \u001b[36mpathname\u001b[0m=\u001b[35m/Users/joaogoncalves/ali-api/app/services/database.py\u001b[0m", "module": "database", "function": "__init__", "filename": "/Users/joaogoncalves/ali-api/app/services/database.py", "line": 62, "environment": "development"}
